insert into akademik.tabel_menu (id, nama_menu, link, icon, is_main_menu)
values  (1, 'Database Siswa', 'siswa', 'fa fa-users', 0),
        (2, 'Database Guru', 'guru', 'fa fa-graduation-cap', 0),
        (3, 'Data Sekolah', 'sekolah', 'fa fa-building', 0),
        (9, 'Data Master', '#', 'fa fa-bars', 0),
        (10, 'Mata Pelajaran', 'mapel', 'fa fa-book', 9),
        (11, 'Ruangan Kelas', 'ruangan', 'fa fa-building', 9),
        (12, 'Jurusan', 'jurusan', 'fa fa-th-large', 9),
        (13, 'Tahun Akademik', 'tahunakademik', 'fa fa-calendar-o', 9),
        (14, 'Jadwal Pelajaran', 'jadwal', 'fa fa-calendar', 0),
        (15, 'Rombongan Belajar', 'rombel', 'fa fa-users', 9),
        (16, 'Laporan Nilai', 'nilai', 'fa fa-file-excel-o', 0),
        (17, 'Pengguna Sistem', 'users', 'fa fa-cubes', 0),
        (19, 'Kurikulum', 'kurikulum', 'fa fa-newspaper-o', 9),
        (20, 'Wali Kelas', 'walikelas', 'fa fa-users', 0),
        (21, 'Form Pembayaran', 'keuangan/form', 'fa fa-shopping-cart', 0),
        (22, 'Peserta Didik', 'siswa/siswa_aktif', 'fa fa-graduation-cap', 0),
        (23, 'Jenis Pembayaran', 'jenis_pembayaran', 'fa fa-credit-card', 0),
        (24, 'Setup Biaya', 'keuangan/setup', 'fa fa-graduation-cap', 0),
        (25, 'Raport Online', 'raport', 'fa fa-graduation-cap', 0),
        (26, 'SMS Gateway', 'sms', 'fa fa-envelope-o', 0),
        (27, 'Phonebook', 'sms_group', 'fa fa-book', 26),
        (28, 'Form SMS', 'sms', 'fa fa-keyboard-o', 26);